CFLAGS:=-c -Wall -Weffc++ -g -std=c++11 -Iinclude
LDFLAGS:=-lboost_system -lboost_thread -pthread

all: Client
	g++ -Wall -Weffc++ -o bin/BGRSclient bin/connectionHandler.o bin/client.o  bin/serverReader.o bin/userReader.o $(LDFLAGS)

Client: bin/connectionHandler.o bin/client.o bin/serverReader.o bin/userReader.o

bin/connectionHandler.o: src/connectionHandler.cpp
	g++ $(CFLAGS) -o bin/connectionHandler.o src/connectionHandler.cpp

bin/client.o: src/client.cpp
	g++ $(CFLAGS) -o bin/client.o src/client.cpp
	

bin/serverReader.o: src/serverReader.cpp
	g++ $(CFLAGS) -o bin/serverReader.o src/serverReader.cpp

bin/userReader.o: src/userReader.cpp
	g++ $(CFLAGS) -o bin/userReader.o src/userReader.cpp
	
.PHONY: clean
clean:
	rm -f bin/*
